<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>Module_Configurator</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Xbox 360 Module Configurator</Title>
	  <Description>A tool used for managing modules on Xbox 360 RGH/Jtag consoles.</Description>
	  <Company>Huskeyyy</Company>
	  <Copyright>© 2024 Tom Gallagher / Huskeyyy. All rights reserved.</Copyright>
	  <Version>1.2.0</Version>
	  <AssemblyVersion>1.2.0</AssemblyVersion>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="JRPC">
      <HintPath>bin\Debug\net8.0-windows\JRPC.dll</HintPath>
    </Reference>
    <Reference Include="XDevkit">
      <HintPath>bin\Debug\net8.0-windows\xDevkit.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>